services:
  sambanas:
    container_name: ${SERVER_NAME}
    image: dperson/samba
    restart: unless-stopped

    ports:
      - "445:445"

    volumes:
      - ${HOST_PATH}:/share
      - ./smb.conf:/etc/samba/smb.conf:ro

    environment:
      USERID: "${USER_ID}"
      GROUPID: "${GROUP_ID}"

      USER: "${USER_1};${PASSWORD_1}"
      USER2: "${USER_2};${PASSWORD_2}"
      #USER3: ...

    command: '-p'