services:
  sambanas:
    container_name: ${SERVER_NAME}
    image: dperson/samba
    restart: unless-stopped

    ports:
      - "445:445"

    volumes:
      - ${HOST_PATH}:/share

    environment:
      USERID: "${USER_ID}"
      GROUPID: "${GROUP_ID}"

    command: '-p -n -u "${SAMBA_USER};${SAMBA_PASSWORD}" -s "NAS;/share;yes;no;no;${SAMBA_USER}"'