services:
  home-nas:
    build: .
    container_name: ${SERVER_NAME}
    restart: unless-stopped

    ports:
      - "445:445"
      - "8000:8000"

    volumes:
      - ${HOST_PATH}:/share
      - ./smb.conf:/etc/samba/smb.conf
      - ./.env:/app/.env
      - samba-passdb:/var/lib/samba

    environment:
      USERID: "${USER_ID}"
      GROUPID: "${GROUP_ID}"

volumes:
  samba-passdb:
