[global]
    workgroup = WORKGROUP
    security = user

    server string = home-nas
    netbios name = home-nas

    map to guest = never

    server min protocol = SMB2

    load printers = no
    printing = bsd
    printcap name = /dev/null

    log level = 1


[Public]
    path = /share/public

    browseable = yes
    guest ok = no

    read only = no
    write list = alice bob

    valid users = alice bob

    force user = smbuser
    force group = smb
    create mask = 0660
    directory mask = 0770


[Documents]
    path = /share/documents

    browseable = yes
    guest ok = no

    read only = yes
    write list = alice

    valid users = alice bob

    force user = smbuser
    force group = smb
    create mask = 0660
    directory mask = 0770


[NewShare]
    path = /share/NEW
    
    browseable = yes
    guest ok = no
            
    read only = no
    write list = alice new
            
    valid users = alice bob new
    
    force user = smbuser
    force group = smb
    create mask = 0660
    directory mask = 0770


[SuperShare]
    path = /share/MegaNiceShare
    
    browseable = yes
    guest ok = no
            
    read only = no
    write list = mitch clare
            
    valid users = mitch clare alice
    
    force user = smbuser
    force group = smb
    create mask = 0660
    directory mask = 0770
